# Generated by Django 5.0.4 on 2024-05-11 23:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Inquilino', max_length=100)),
                ('identidade', models.CharField(help_text='Numero da Indentidade', max_length=100)),
                ('orgao', models.CharField(help_text='Orgão emissor', max_length=100)),
                ('nascimento', models.DateField()),
                ('nacionalidade', models.CharField(help_text='Nacionalidade', max_length=100)),
                ('proficao', models.CharField(help_text='Profissão', max_length=100)),
                ('ddd', models.CharField(help_text='Digite o DDD', max_length=2, validators=[django.core.validators.RegexValidator(message='O DDD deve conter 2 dígitos.', regex='^\\d{2}$')])),
                ('tel_cont1', models.CharField(help_text='Digite o número de telefone', max_length=9, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter 8 ou 9 dígitos.', regex='^\\d{8,9}$')])),
                ('contato2', models.CharField(help_text='Digite o número de telefone', max_length=9, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter 8 ou 9 dígitos.', regex='^\\d{8,9}$')])),
                ('email', models.EmailField(help_text='E-mail de contato', max_length=254)),
                ('apartamento', models.IntegerField()),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloco.bloco')),
            ],
        ),
        migrations.CreateModel(
            name='Dependentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Dependente', max_length=100)),
                ('parentesco', models.CharField(help_text='Parentesco', max_length=100)),
                ('identidade', models.CharField(help_text='Numero da Indentidade', max_length=100)),
                ('orgao', models.CharField(help_text='Orgão emissor', max_length=100)),
                ('nascimento', models.DateField()),
                ('ddd', models.CharField(help_text='Digite o DDD', max_length=2, validators=[django.core.validators.RegexValidator(message='O DDD deve conter 2 dígitos.', regex='^\\d{2}$')])),
                ('tel_cont1', models.CharField(help_text='Digite o número de telefone', max_length=9, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter 8 ou 9 dígitos.', regex='^\\d{8,9}$')])),
                ('contato2', models.CharField(help_text='Digite o número de telefone', max_length=9, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter 8 ou 9 dígitos.', regex='^\\d{8,9}$')])),
                ('email', models.EmailField(help_text='E-mail de contato', max_length=254)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inquilino.inquilinos')),
            ],
        ),
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(help_text='Especie', max_length=100)),
                ('quantidade', models.IntegerField()),
                ('vacinacao', models.CharField(help_text='Vacinado', max_length=100)),
                ('dono', models.ManyToManyField(to='inquilino.inquilinos')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa do veículo', max_length=100)),
                ('marca', models.CharField(help_text='marca do veículo', max_length=100)),
                ('modelo', models.CharField(help_text='modelo do veículo', max_length=100)),
                ('cor', models.CharField(help_text='cor do veículo', max_length=100)),
                ('dono', models.ManyToManyField(to='inquilino.inquilinos')),
            ],
        ),
    ]
