# Generated by Django 5.0.4 on 2024-06-04 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        ('departamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome funcionário', max_length=100)),
                ('foto_usuario', models.ImageField(blank=True, null=True, upload_to='fotos_usuario/')),
                ('cargo', models.ManyToManyField(related_name='funcionarios_cargo', to='departamentos.departamentos')),
                ('condominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominios.condominios')),
                ('user', models.ManyToManyField(related_name='Nome_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
