# Generated by Django 5.0.4 on 2024-06-04 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('funcionarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='cargo',
            field=models.ManyToManyField(blank=True, null=True, related_name='funcionarios_cargo', to='departamentos.departamentos'),
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='user',
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Nome_usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
