# Generated by Django 5.0.4 on 2024-06-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_departamentos_condominio'),
        ('funcionarios', '0004_alter_funcionarios_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='cargo',
            field=models.ManyToManyField(blank=True, related_name='funcionarios_cargo', to='departamentos.departamentos'),
        ),
    ]
