# Generated by Django 5.0.4 on 2024-05-11 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquilino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(help_text='Horario', max_length=100)),
                ('dia', models.DateField()),
                ('periodo', models.CharField(help_text='Manhã, Tarde ou Noite', max_length=100)),
                ('categoria', models.CharField(choices=[('Ch', 'Churrasqueira'), ('SF', 'Salão de Festas'), ('SJ', 'Salão de Jogos'), ('Md', 'Mudança')], max_length=100)),
                ('bloco', models.IntegerField()),
                ('apartamento', models.IntegerField()),
                ('inquilino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquilino.inquilinos')),
            ],
        ),
    ]
