# Generated by Django 5.0.4 on 2024-05-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(help_text='Horario', max_length=100)),
                ('dia', models.DateField()),
                ('periodo', models.CharField(help_text='Manhã, Tarde ou Noite', max_length=100)),
                ('tipo', models.CharField(choices=[('Ch', 'Churrasqueira'), ('SF', 'Salão de Festas'), ('SJ', 'Salão de Jogos')], max_length=100)),
            ],
        ),
    ]
