# Generated by Django 5.0.4 on 2024-06-04 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Proprietário', max_length=100)),
                ('identidade', models.CharField(help_text='Numero da Indentidade', max_length=100)),
                ('orgao', models.CharField(help_text='Orgão emissor', max_length=100)),
                ('nascimento', models.DateField()),
                ('nacionalidade', models.CharField(help_text='Nacionalidade', max_length=100)),
                ('proficao', models.CharField(help_text='Profissão', max_length=100)),
                ('ddd', models.CharField(help_text='Digite o DDD', max_length=2, validators=[django.core.validators.RegexValidator(message='O DDD deve conter 2 dígitos.', regex='^\\d{2}$')])),
                ('tel_cont1', models.CharField(help_text='Digite o número de telefone', max_length=9, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter 8 ou 9 dígitos.', regex='^\\d{8,9}$')])),
                ('contato2', models.CharField(help_text='Digite o número de telefone', max_length=9, validators=[django.core.validators.RegexValidator(message='O número de telefone deve conter 8 ou 9 dígitos.', regex='^\\d{8,9}$')])),
                ('email', models.EmailField(help_text='E-mail de contato', max_length=254)),
                ('bloco', models.IntegerField()),
                ('apartamento', models.IntegerField()),
            ],
        ),
    ]
