# Generated by Django 5.0.4 on 2024-06-25 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0002_apartamentos_condominio'),
        ('inquilino', '0002_inquilinos_condominio'),
        ('proprietario', '0002_proprietario_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentos',
            name='morador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inquilino.inquilinos'),
        ),
        migrations.AlterField(
            model_name='apartamentos',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='proprietario.proprietario'),
        ),
    ]
