# Generated by Django 5.0.4 on 2024-06-25 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0004_alter_apartamentos_morador_and_more'),
        ('bloco', '0004_alter_bloco_condominio_alter_bloco_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentos',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bloco.bloco'),
        ),
    ]
