# Generated by Django 5.0.4 on 2024-06-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do departamento', max_length=100)),
                ('condominio', models.ManyToManyField(to='condominios.condominios')),
            ],
        ),
    ]
