# Generated by Django 5.0.4 on 2024-06-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        ('departamentos', '0002_alter_departamentos_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='condominio',
            field=models.ManyToManyField(blank=True, to='condominios.condominios'),
        ),
    ]
