# Generated by Django 5.0.4 on 2024-05-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('condominio', models.ManyToManyField(to='condominios.condominios')),
            ],
        ),
    ]
