# Generated by Django 5.0.4 on 2024-06-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloco', '0003_alter_bloco_condominio'),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='condominio',
            field=models.ManyToManyField(blank=True, to='condominios.condominios'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
